#!/usr/bin/env python3
"""
NF4 反量化 —— 输入数据生成

使用 bitsandbytes 对随机正态分布权重矩阵进行 NF4 量化（双重量化），
将量化结果按二进制格式写入文件，同时保存 bitsandbytes 解量化的参考输出。

二进制文件格式:
  [header]
    num_rows   : int64
    num_cols   : int64
    blocksize  : int32
  [data]
    packed_weights : uint8[N/2]          每字节存两个 4-bit 索引
    absmax_q       : uint8[num_blocks]   一级量化缩放因子
    absmax2        : float16[num_groups] 二级缩放因子
    code2          : float16[256]        二级码表
    offset         : float32            量化偏移
"""

import argparse
import math
import os
import struct
import sys

import numpy as np
import torch
import bitsandbytes.functional as F


def parse_args():
    parser = argparse.ArgumentParser(description="NF4 量化数据生成")
    parser.add_argument("--rows", type=int, default=4096)
    parser.add_argument("--cols", type=int, default=4096)
    parser.add_argument("--blocksize", type=int, default=64,
                        choices=[64, 128, 256, 512, 1024, 2048, 4096])
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--compute_type", type=str, default="bf16",
                        choices=["bf16", "fp16"])
    parser.add_argument("--outdir", type=str, default=None,
                        help="输出目录 (默认: <项目根>/data)")
    return parser.parse_args()


def generate_and_save(rows, cols, blocksize, seed, compute_type, outdir):
    os.makedirs(outdir, exist_ok=True)

    # 1. 生成随机权重
    torch.manual_seed(seed)
    weight = torch.randn(rows, cols, dtype=torch.float16, device="cuda")
    print(f"[generate] shape=({rows}, {cols}), dtype=float16, seed={seed}")

    # 2. NF4 量化 (双重量化)
    quant, state = F.quantize_4bit(
        weight, quant_type="nf4", blocksize=blocksize,
        compress_statistics=True,
    )

    n_elements = rows * cols
    num_blocks = math.ceil(n_elements / blocksize)

    assert state.state2 is not None, "compress_statistics=True 应启用双重量化"
    s2 = state.state2
    num_groups = s2.absmax.shape[0]

    print(f"[generate] blocksize={blocksize}, num_blocks={num_blocks}, "
          f"num_groups={num_groups}, s2_blocksize={s2.blocksize}")

    # 3. 提取数据
    packed_weights = quant.cpu().numpy().astype(np.uint8).flatten()
    assert packed_weights.shape[0] == n_elements // 2

    absmax_q = state.absmax.cpu().numpy().astype(np.uint8)
    assert absmax_q.shape[0] == num_blocks

    absmax2 = s2.absmax.cpu().numpy().astype(np.float16)
    code2 = s2.code.cpu().numpy().astype(np.float16)
    assert code2.shape[0] == 256

    offset_val = state.offset.cpu().item() if state.offset is not None else 0.0

    # 4. 写二进制权重文件
    tag = f"{rows}x{cols}_bs{blocksize}"
    weight_file = os.path.join(outdir, f"nf4_weights_{tag}.bin")

    with open(weight_file, "wb") as f:
        f.write(struct.pack("<q", rows))
        f.write(struct.pack("<q", cols))
        f.write(struct.pack("<i", blocksize))
        f.write(packed_weights.tobytes())
        f.write(absmax_q.tobytes())
        f.write(absmax2.tobytes())
        f.write(code2.tobytes())
        f.write(struct.pack("<f", offset_val))

    print(f"[generate] 权重文件: {weight_file} ({os.path.getsize(weight_file)} bytes)")

    # 5. bitsandbytes 参考解量化输出
    deq = F.dequantize_4bit(quant, state)
    if compute_type == "bf16":
        ref_output = deq.to(torch.bfloat16)
        ref_bytes = ref_output.cpu().view(torch.uint16).numpy()
    else:
        ref_output = deq.to(torch.float16)
        ref_bytes = ref_output.cpu().numpy()

    ref_file = os.path.join(outdir, f"nf4_ref_output_{tag}_{compute_type}.bin")
    ref_bytes.tofile(ref_file)
    print(f"[generate] 参考输出: {ref_file} ({os.path.getsize(ref_file)} bytes)")

    # 6. 量化误差
    mae = (deq.half() - weight).abs().mean().item()
    max_err = (deq.half() - weight).abs().max().item()
    print(f"[generate] 量化误差: MAE={mae:.6f}, MaxErr={max_err:.6f}")

    # 7. 参数摘要文件
    params_file = os.path.join(outdir, f"params_{tag}.txt")
    with open(params_file, "w") as f:
        f.write(f"num_rows = {rows}\n")
        f.write(f"num_cols = {cols}\n")
        f.write(f"blocksize = {blocksize}\n")
        f.write(f"compute_type = \"{compute_type}\"\n")
        f.write(f"num_blocks = {num_blocks}\n")
        f.write(f"num_groups = {num_groups}\n")
        f.write(f"state2_blocksize = {s2.blocksize}\n")
        f.write(f"offset = {offset_val}\n")
        f.write(f"seed = {seed}\n")

    # 8. NF4 码表 (供 kernel 硬编码参考)
    nf4_code = state.code.cpu().tolist()
    code_file = os.path.join(outdir, "nf4_code.txt")
    with open(code_file, "w") as f:
        f.write("// NF4 lookup table (16 values, index 0-15)\n")
        f.write("// Generated by bitsandbytes create_normal_map()\n")
        f.write("__constant__ float NF4_DEQUANT_TABLE[16] = {\n")
        for i, val in enumerate(nf4_code):
            comma = "," if i < 15 else ""
            f.write(f"    {val:.10f}{comma}  // index {i}\n")
        f.write("};\n")

    print(f"[generate] 完成")


def main():
    args = parse_args()
    outdir = args.outdir
    if outdir is None:
        outdir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
    generate_and_save(
        rows=args.rows, cols=args.cols, blocksize=args.blocksize,
        seed=args.seed, compute_type=args.compute_type, outdir=outdir,
    )


if __name__ == "__main__":
    main()
